INST_TARGETS = \
    T0_int.inst.hh \


T0_int.inst.hh : impl.h
	@echo [GEN]  "<int>" "($@)"
	@echo "#line 1" '"container/hashmap/impl.h"' > $@
	@sed -e "s/@(TKey)/int/g" -e "s/@(MANGLE)/_hashmap_T0_int/g" $< >> $@

